# Generated by Django 3.2.6 on 2024-06-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='waktuPosting',
            new_name='publish',
        ),
        migrations.AddField(
            model_name='post',
            name='update',
            field=models.DateTimeField(default=''),
        ),
    ]
