# Generated by Django 3.2.6 on 2024-06-05 12:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20240605_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='waktuPosting',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
