# Generated by Django 3.2.6 on 2024-06-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_waktuposting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='waktuPosting',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
